-- ============================================================
-- Project      : NHPC Website
-- File         : 01_lookup_tables.sql
-- Module       : Lookup Tables
-- Description  : Reference data tables
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: states
-- ============================================================

CREATE TABLE states (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(100) NOT NULL,

    code VARCHAR(30) NOT NULL,

    description TEXT,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_states PRIMARY KEY (id),

    CONSTRAINT uq_states_name UNIQUE (name),

    CONSTRAINT uq_states_code UNIQUE (code),

    CONSTRAINT chk_states_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_states_name
ON states(name);

CREATE INDEX idx_states_code
ON states(code);

CREATE TRIGGER trg_states_updated_at
BEFORE UPDATE ON states
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: capacity_units
-- ============================================================

CREATE TABLE capacity_units (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(100) NOT NULL,

    code VARCHAR(30) NOT NULL,

    description TEXT,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_capacity_units PRIMARY KEY (id),

    CONSTRAINT uq_capacity_units_name UNIQUE (name),

    CONSTRAINT uq_capacity_units_code UNIQUE (code),

    CONSTRAINT chk_capacity_units_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_capacity_units_name
ON capacity_units(name);

CREATE INDEX idx_capacity_units_code
ON capacity_units(code);

CREATE TRIGGER trg_capacity_units_updated_at
BEFORE UPDATE ON capacity_units
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: project_types
-- ============================================================

CREATE TABLE project_types (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(100) NOT NULL,

    code VARCHAR(30) NOT NULL,

    description TEXT,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_project_types PRIMARY KEY (id),

    CONSTRAINT uq_project_types_name UNIQUE (name),

    CONSTRAINT uq_project_types_code UNIQUE (code),

    CONSTRAINT chk_project_types_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_project_types_name
ON project_types(name);

CREATE INDEX idx_project_types_code
ON project_types(code);

CREATE TRIGGER trg_project_types_updated_at
BEFORE UPDATE ON project_types
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: project_statuses
-- ============================================================

CREATE TABLE project_statuses (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(100) NOT NULL,

    code VARCHAR(30) NOT NULL,

    description TEXT,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_project_statuses PRIMARY KEY (id),

    CONSTRAINT uq_project_statuses_name UNIQUE (name),

    CONSTRAINT uq_project_statuses_code UNIQUE (code),

    CONSTRAINT chk_project_statuses_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_project_statuses_name
ON project_statuses(name);

CREATE INDEX idx_project_statuses_code
ON project_statuses(code);

CREATE TRIGGER trg_project_statuses_updated_at
BEFORE UPDATE ON project_statuses
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: news_categories
-- ============================================================

CREATE TABLE news_categories (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(100) NOT NULL,

    code VARCHAR(30) NOT NULL,

    description TEXT,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_news_categories PRIMARY KEY (id),

    CONSTRAINT uq_news_categories_name UNIQUE (name),

    CONSTRAINT uq_news_categories_code UNIQUE (code),

    CONSTRAINT chk_news_categories_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_news_categories_name ON news_categories(name);
CREATE INDEX idx_news_categories_code ON news_categories(code);

CREATE TRIGGER trg_news_categories_updated_at
BEFORE UPDATE ON news_categories
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: tender_categories
-- ============================================================

CREATE TABLE tender_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tender_categories PRIMARY KEY(id),
    CONSTRAINT uq_tender_categories_name UNIQUE(name),
    CONSTRAINT uq_tender_categories_code UNIQUE(code),
    CONSTRAINT chk_tender_categories_display_order CHECK(display_order>0)
);

CREATE INDEX idx_tender_categories_name ON tender_categories(name);
CREATE INDEX idx_tender_categories_code ON tender_categories(code);

CREATE TRIGGER trg_tender_categories_updated_at
BEFORE UPDATE ON tender_categories
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: tender_statuses
-- ============================================================

CREATE TABLE tender_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tender_statuses PRIMARY KEY(id),
    CONSTRAINT uq_tender_statuses_name UNIQUE(name),
    CONSTRAINT uq_tender_statuses_code UNIQUE(code),
    CONSTRAINT chk_tender_statuses_display_order CHECK(display_order>0)
);

CREATE INDEX idx_tender_statuses_name ON tender_statuses(name);
CREATE INDEX idx_tender_statuses_code ON tender_statuses(code);

CREATE TRIGGER trg_tender_statuses_updated_at
BEFORE UPDATE ON tender_statuses
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: employment_types
-- ============================================================

CREATE TABLE employment_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_employment_types PRIMARY KEY(id),
    CONSTRAINT uq_employment_types_name UNIQUE(name),
    CONSTRAINT uq_employment_types_code UNIQUE(code),
    CONSTRAINT chk_employment_types_display_order CHECK(display_order>0)
);

CREATE INDEX idx_employment_types_name ON employment_types(name);
CREATE INDEX idx_employment_types_code ON employment_types(code);

CREATE TRIGGER trg_employment_types_updated_at
BEFORE UPDATE ON employment_types
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: application_statuses
-- ============================================================

CREATE TABLE application_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_application_statuses PRIMARY KEY(id),
    CONSTRAINT uq_application_statuses_name UNIQUE(name),
    CONSTRAINT uq_application_statuses_code UNIQUE(code),
    CONSTRAINT chk_application_statuses_display_order CHECK(display_order>0)
);

CREATE INDEX idx_application_statuses_name ON application_statuses(name);
CREATE INDEX idx_application_statuses_code ON application_statuses(code);

CREATE TRIGGER trg_application_statuses_updated_at
BEFORE UPDATE ON application_statuses
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: leadership_levels
-- ============================================================

CREATE TABLE leadership_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_leadership_levels PRIMARY KEY(id),
    CONSTRAINT uq_leadership_levels_name UNIQUE(name),
    CONSTRAINT uq_leadership_levels_code UNIQUE(code),
    CONSTRAINT chk_leadership_levels_display_order CHECK(display_order>0)
);

CREATE INDEX idx_leadership_levels_name ON leadership_levels(name);
CREATE INDEX idx_leadership_levels_code ON leadership_levels(code);

CREATE TRIGGER trg_leadership_levels_updated_at
BEFORE UPDATE ON leadership_levels
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: sustainability_types
-- ============================================================

CREATE TABLE sustainability_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_sustainability_types PRIMARY KEY(id),
    CONSTRAINT uq_sustainability_types_name UNIQUE(name),
    CONSTRAINT uq_sustainability_types_code UNIQUE(code),
    CONSTRAINT chk_sustainability_types_display_order CHECK(display_order>0)
);

CREATE INDEX idx_sustainability_types_name ON sustainability_types(name);
CREATE INDEX idx_sustainability_types_code ON sustainability_types(code);

CREATE TRIGGER trg_sustainability_types_updated_at
BEFORE UPDATE ON sustainability_types
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: investor_document_types
-- ============================================================

CREATE TABLE investor_document_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_investor_document_types PRIMARY KEY(id),
    CONSTRAINT uq_investor_document_types_name UNIQUE(name),
    CONSTRAINT uq_investor_document_types_code UNIQUE(code),
    CONSTRAINT chk_investor_document_types_display_order CHECK(display_order>0)
);

CREATE INDEX idx_investor_document_types_name ON investor_document_types(name);
CREATE INDEX idx_investor_document_types_code ON investor_document_types(code);

CREATE TRIGGER trg_investor_document_types_updated_at
BEFORE UPDATE ON investor_document_types
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: financial_years
-- ============================================================

CREATE TABLE financial_years (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    label VARCHAR(20) NOT NULL,

    start_year INTEGER NOT NULL,

    end_year INTEGER NOT NULL,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_financial_years PRIMARY KEY(id),

    CONSTRAINT uq_financial_years_label UNIQUE(label),

    CONSTRAINT chk_financial_years_order
        CHECK(start_year < end_year),

    CONSTRAINT chk_financial_years_display_order
        CHECK(display_order > 0)

);

CREATE INDEX idx_financial_years_label
ON financial_years(label);

CREATE TRIGGER trg_financial_years_updated_at
BEFORE UPDATE ON financial_years
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: office_types
-- ============================================================

CREATE TABLE office_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_office_types PRIMARY KEY(id),
    CONSTRAINT uq_office_types_name UNIQUE(name),
    CONSTRAINT uq_office_types_code UNIQUE(code),
    CONSTRAINT chk_office_types_display_order CHECK(display_order>0)
);

CREATE INDEX idx_office_types_name ON office_types(name);
CREATE INDEX idx_office_types_code ON office_types(code);

CREATE TRIGGER trg_office_types_updated_at
BEFORE UPDATE ON office_types
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: message_statuses
-- ============================================================

CREATE TABLE message_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_message_statuses PRIMARY KEY(id),
    CONSTRAINT uq_message_statuses_name UNIQUE(name),
    CONSTRAINT uq_message_statuses_code UNIQUE(code),
    CONSTRAINT chk_message_statuses_display_order CHECK(display_order>0)
);

CREATE INDEX idx_message_statuses_name ON message_statuses(name);
CREATE INDEX idx_message_statuses_code ON message_statuses(code);

CREATE TRIGGER trg_message_statuses_updated_at
BEFORE UPDATE ON message_statuses
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();