-- ============================================================
-- Project      : NHPC Website
-- File         : 02_core_system.sql
-- Module       : Core System
-- Description  : Authentication & Digital Asset Management
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: admins
-- ============================================================

CREATE TABLE admins (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    full_name VARCHAR(150) NOT NULL,

    email VARCHAR(255) NOT NULL,

    password_hash TEXT NOT NULL,

    role VARCHAR(50) NOT NULL,

    last_login_at TIMESTAMPTZ,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_admins PRIMARY KEY (id),

    CONSTRAINT uq_admins_email UNIQUE (email)

);

CREATE INDEX idx_admins_email
ON admins(email);

CREATE TRIGGER trg_admins_updated_at
BEFORE UPDATE ON admins
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: media_folders
-- ============================================================

CREATE TABLE media_folders (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    parent_id BIGINT,

    name VARCHAR(150) NOT NULL,

    description TEXT,

    display_order INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_media_folders PRIMARY KEY (id),

    CONSTRAINT fk_media_folders_parent
        FOREIGN KEY (parent_id)
        REFERENCES media_folders(id)
        ON DELETE SET NULL,

    CONSTRAINT chk_media_folders_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_media_folders_parent
ON media_folders(parent_id);

CREATE INDEX idx_media_folders_name
ON media_folders(name);

CREATE TRIGGER trg_media_folders_updated_at
BEFORE UPDATE ON media_folders
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: media_files
-- ============================================================

CREATE TABLE media_files (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    folder_id BIGINT,

    original_name VARCHAR(255) NOT NULL,

    stored_name VARCHAR(255) NOT NULL,

    mime_type VARCHAR(100) NOT NULL,

    extension VARCHAR(20) NOT NULL,

    size_bytes BIGINT NOT NULL,

    width INTEGER,

    height INTEGER,

    duration_seconds NUMERIC(10,2),

    storage_provider VARCHAR(50) NOT NULL DEFAULT 'LOCAL',

    storage_path TEXT NOT NULL,

    alt_text VARCHAR(255),

    caption TEXT,

    uploaded_by BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_media_files PRIMARY KEY (id),

    CONSTRAINT fk_media_files_folder
        FOREIGN KEY (folder_id)
        REFERENCES media_folders(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_media_files_uploaded_by
        FOREIGN KEY (uploaded_by)
        REFERENCES admins(id)

);

CREATE INDEX idx_media_files_folder
ON media_files(folder_id);

CREATE INDEX idx_media_files_uploaded_by
ON media_files(uploaded_by);

CREATE INDEX idx_media_files_storage_provider
ON media_files(storage_provider);

CREATE TRIGGER trg_media_files_updated_at
BEFORE UPDATE ON media_files
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: media_file_links
-- ============================================================

CREATE TABLE media_file_links (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    media_file_id BIGINT NOT NULL,

    entity_type VARCHAR(50) NOT NULL,

    entity_id BIGINT NOT NULL,

    purpose VARCHAR(100) NOT NULL,

    display_order INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_media_file_links PRIMARY KEY (id),

    CONSTRAINT fk_media_file_links_media
        FOREIGN KEY (media_file_id)
        REFERENCES media_files(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_media_file_links_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_media_links_media
ON media_file_links(media_file_id);

CREATE INDEX idx_media_links_entity
ON media_file_links(entity_type, entity_id);

CREATE INDEX idx_media_links_purpose
ON media_file_links(purpose);