-- ============================================================
-- Project      : NHPC Website
-- File         : 03_homepage.sql
-- Module       : Homepage
-- Description  : Homepage Configuration & Content
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: homepage_sections
-- ============================================================

CREATE TABLE homepage_sections (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    section_key VARCHAR(50) NOT NULL,

    title VARCHAR(255),

    subtitle TEXT,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_visible BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_homepage_sections PRIMARY KEY (id),

    CONSTRAINT uq_homepage_sections_key UNIQUE (section_key),

    CONSTRAINT chk_homepage_sections_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_homepage_sections_order
ON homepage_sections(display_order);

CREATE INDEX idx_homepage_sections_visible
ON homepage_sections(is_visible);

CREATE TRIGGER trg_homepage_sections_updated_at
BEFORE UPDATE ON homepage_sections
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: homepage_content
-- ============================================================

CREATE TABLE homepage_content (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    section_id BIGINT NOT NULL,

    content_key VARCHAR(100) NOT NULL,

    content_value TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_homepage_content PRIMARY KEY (id),

    CONSTRAINT fk_homepage_content_section
        FOREIGN KEY (section_id)
        REFERENCES homepage_sections(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_homepage_content_key
        UNIQUE(section_id, content_key)

);

CREATE INDEX idx_homepage_content_section
ON homepage_content(section_id);

CREATE TRIGGER trg_homepage_content_updated_at
BEFORE UPDATE ON homepage_content
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: hero_buttons
-- ============================================================

CREATE TABLE hero_buttons (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    section_id BIGINT NOT NULL,

    label VARCHAR(100) NOT NULL,

    url TEXT NOT NULL,

    button_style VARCHAR(30) NOT NULL,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_hero_buttons PRIMARY KEY (id),

    CONSTRAINT fk_hero_buttons_section
        FOREIGN KEY (section_id)
        REFERENCES homepage_sections(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_hero_buttons_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_hero_buttons_section
ON hero_buttons(section_id);

CREATE INDEX idx_hero_buttons_order
ON hero_buttons(display_order);

CREATE TRIGGER trg_hero_buttons_updated_at
BEFORE UPDATE ON hero_buttons
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: statistics
-- ============================================================

CREATE TABLE statistics (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    label VARCHAR(150) NOT NULL,

    value VARCHAR(100) NOT NULL,

    icon VARCHAR(100),

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_statistics PRIMARY KEY (id),

    CONSTRAINT chk_statistics_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_statistics_order
ON statistics(display_order);

CREATE INDEX idx_statistics_active
ON statistics(is_active);

CREATE TRIGGER trg_statistics_updated_at
BEFORE UPDATE ON statistics
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: navigation_menu
-- Description : Website Navigation Menu
-- ============================================================

CREATE TABLE navigation_menu (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    parent_id BIGINT,

    label VARCHAR(100) NOT NULL,

    route VARCHAR(255) NOT NULL,

    icon VARCHAR(100),

    menu_location VARCHAR(30) NOT NULL DEFAULT 'HEADER',

    display_order INTEGER NOT NULL DEFAULT 1,

    is_visible BOOLEAN NOT NULL DEFAULT TRUE,

    open_in_new_tab BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_navigation_menu PRIMARY KEY (id),

    CONSTRAINT fk_navigation_menu_parent
        FOREIGN KEY (parent_id)
        REFERENCES navigation_menu(id)
        ON DELETE SET NULL,

    CONSTRAINT uq_navigation_menu_route
        UNIQUE (route),

    CONSTRAINT chk_navigation_menu_display_order
        CHECK (display_order > 0),

    CONSTRAINT chk_navigation_menu_location
        CHECK (menu_location IN ('HEADER', 'FOOTER'))

);

CREATE INDEX idx_navigation_menu_parent
ON navigation_menu(parent_id);

CREATE INDEX idx_navigation_menu_order
ON navigation_menu(display_order);

CREATE INDEX idx_navigation_menu_visible
ON navigation_menu(is_visible);

CREATE INDEX idx_navigation_menu_location
ON navigation_menu(menu_location);

CREATE TRIGGER trg_navigation_menu_updated_at
BEFORE UPDATE ON navigation_menu
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();
