-- ============================================================
-- Project      : NHPC Website
-- File         : 04_operational_power_stations.sql
-- Module       : Operational Power Stations
-- Description  : Operational generating stations of NHPC
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

CREATE TABLE operational_power_stations (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(200) NOT NULL,

    slug VARCHAR(250) NOT NULL,

    state_id BIGINT NOT NULL,

    project_type_id BIGINT NOT NULL,

    installed_capacity NUMERIC(10,2) NOT NULL,

    capacity_unit_id BIGINT NOT NULL,

    commissioned_on DATE,

    latitude DECIMAL(10,7),

    longitude DECIMAL(10,7),

    description TEXT,

    is_featured BOOLEAN NOT NULL DEFAULT FALSE,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_operational_power_stations
        PRIMARY KEY (id),

    CONSTRAINT uq_operational_power_stations_slug
        UNIQUE (slug),

    CONSTRAINT fk_ops_state
        FOREIGN KEY (state_id)
        REFERENCES states(id),

    CONSTRAINT fk_ops_project_type
        FOREIGN KEY (project_type_id)
        REFERENCES project_types(id),

    CONSTRAINT fk_ops_capacity_unit
        FOREIGN KEY (capacity_unit_id)
        REFERENCES capacity_units(id),

    CONSTRAINT chk_ops_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_ops_slug
ON operational_power_stations(slug);

CREATE INDEX idx_ops_state
ON operational_power_stations(state_id);

CREATE INDEX idx_ops_featured
ON operational_power_stations(is_featured);

CREATE INDEX idx_ops_active
ON operational_power_stations(is_active);

CREATE INDEX idx_ops_display_order
ON operational_power_stations(display_order);

CREATE TRIGGER trg_operational_power_stations_updated_at
BEFORE UPDATE ON operational_power_stations
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();