-- ============================================================
-- Project      : NHPC Website
-- File         : 05_projects.sql
-- Module       : Projects
-- Description  : NHPC Projects
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: projects
-- ============================================================

CREATE TABLE projects (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(200) NOT NULL,

    slug VARCHAR(250) NOT NULL,

    state_id BIGINT NOT NULL,

    project_type_id BIGINT NOT NULL,

    project_status_id BIGINT NOT NULL,

    capacity NUMERIC(12,2) NOT NULL,

    capacity_unit_id BIGINT NOT NULL,

    summary TEXT,

    latitude DECIMAL(10,7),

    longitude DECIMAL(10,7),

    is_featured BOOLEAN NOT NULL DEFAULT FALSE,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_projects
        PRIMARY KEY(id),

    CONSTRAINT uq_projects_slug
        UNIQUE(slug),

    CONSTRAINT fk_projects_state
        FOREIGN KEY(state_id)
        REFERENCES states(id),

    CONSTRAINT fk_projects_type
        FOREIGN KEY(project_type_id)
        REFERENCES project_types(id),

    CONSTRAINT fk_projects_status
        FOREIGN KEY(project_status_id)
        REFERENCES project_statuses(id),

    CONSTRAINT fk_projects_capacity_unit
        FOREIGN KEY(capacity_unit_id)
        REFERENCES capacity_units(id),

    CONSTRAINT chk_projects_display_order
        CHECK(display_order > 0)

);

CREATE INDEX idx_projects_slug
ON projects(slug);

CREATE INDEX idx_projects_state
ON projects(state_id);

CREATE INDEX idx_projects_type
ON projects(project_type_id);

CREATE INDEX idx_projects_status
ON projects(project_status_id);

CREATE INDEX idx_projects_featured
ON projects(is_featured);

CREATE INDEX idx_projects_active
ON projects(is_active);

CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: project_details
-- ============================================================

CREATE TABLE project_details (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    project_id BIGINT NOT NULL,

    overview TEXT,

    history TEXT,

    highlights TEXT,

    current_status TEXT,

    future_plan TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_project_details
        PRIMARY KEY(id),

    CONSTRAINT uq_project_details_project
        UNIQUE(project_id),

    CONSTRAINT fk_project_details_project
        FOREIGN KEY(project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE

);

CREATE TRIGGER trg_project_details_updated_at
BEFORE UPDATE ON project_details
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: project_technical_details
-- ============================================================

CREATE TABLE project_technical_details (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    project_id BIGINT NOT NULL,

    parameter VARCHAR(150) NOT NULL,

    value TEXT NOT NULL,

    display_order INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_project_technical_details
        PRIMARY KEY(id),

    CONSTRAINT fk_project_technical_project
        FOREIGN KEY(project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_project_technical_display_order
        CHECK(display_order > 0)

);

CREATE INDEX idx_project_technical_project
ON project_technical_details(project_id);

CREATE TRIGGER trg_project_technical_updated_at
BEFORE UPDATE ON project_technical_details
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: project_documents
-- ============================================================

CREATE TABLE project_documents (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    project_id BIGINT NOT NULL,

    media_file_id BIGINT NOT NULL,

    title VARCHAR(200) NOT NULL,

    display_order INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_project_documents
        PRIMARY KEY(id),

    CONSTRAINT fk_project_documents_project
        FOREIGN KEY(project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_project_documents_media
        FOREIGN KEY(media_file_id)
        REFERENCES media_files(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_project_documents_display_order
        CHECK(display_order > 0)

);

CREATE INDEX idx_project_documents_project
ON project_documents(project_id);

CREATE TRIGGER trg_project_documents_updated_at
BEFORE UPDATE ON project_documents
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();