-- ============================================================
-- Project      : NHPC Website
-- File         : 06_news.sql
-- Module       : News
-- Description  : News and Documents
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: news
-- ============================================================

CREATE TABLE news (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    title VARCHAR(255) NOT NULL,

    slug VARCHAR(255) NOT NULL,

    news_category_id BIGINT NOT NULL,

    summary TEXT,

    content TEXT,

    published_at TIMESTAMPTZ,

    is_featured BOOLEAN NOT NULL DEFAULT FALSE,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_news PRIMARY KEY (id),

    CONSTRAINT uq_news_slug UNIQUE (slug),

    CONSTRAINT fk_news_category
        FOREIGN KEY (news_category_id)
        REFERENCES news_categories(id),

    CONSTRAINT chk_news_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_news_slug ON news(slug);
CREATE INDEX idx_news_category ON news(news_category_id);
CREATE INDEX idx_news_published ON news(published_at);
CREATE INDEX idx_news_featured ON news(is_featured);

CREATE TRIGGER trg_news_updated_at
BEFORE UPDATE ON news
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: news_documents
-- ============================================================

CREATE TABLE news_documents (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    news_id BIGINT NOT NULL,

    media_file_id BIGINT NOT NULL,

    title VARCHAR(200) NOT NULL,

    display_order INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_news_documents PRIMARY KEY (id),

    CONSTRAINT fk_news_documents_news
        FOREIGN KEY (news_id)
        REFERENCES news(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_news_documents_media
        FOREIGN KEY (media_file_id)
        REFERENCES media_files(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_news_documents_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_news_documents_news
ON news_documents(news_id);

CREATE TRIGGER trg_news_documents_updated_at
BEFORE UPDATE ON news_documents
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();