-- ============================================================
-- Project      : NHPC Website
-- File         : 07_tenders.sql
-- Module       : Tenders
-- Description  : Tenders  and Documents
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: tenders
-- ============================================================

CREATE TABLE tenders (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    title VARCHAR(255) NOT NULL,

    tender_number VARCHAR(100) NOT NULL,

    slug VARCHAR(255) NOT NULL,

    tender_category_id BIGINT NOT NULL,

    tender_status_id BIGINT NOT NULL,

    summary TEXT,

    description TEXT,

    published_at TIMESTAMPTZ,

    opening_date DATE,

    closing_date DATE,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tenders PRIMARY KEY (id),

    CONSTRAINT uq_tenders_slug UNIQUE (slug),

    CONSTRAINT uq_tenders_number UNIQUE (tender_number),

    CONSTRAINT fk_tenders_category
        FOREIGN KEY (tender_category_id)
        REFERENCES tender_categories(id),

    CONSTRAINT fk_tenders_status
        FOREIGN KEY (tender_status_id)
        REFERENCES tender_statuses(id),

    CONSTRAINT chk_tenders_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_tenders_slug
ON tenders(slug);

CREATE INDEX idx_tenders_category
ON tenders(tender_category_id);

CREATE INDEX idx_tenders_status
ON tenders(tender_status_id);

CREATE INDEX idx_tenders_closing
ON tenders(closing_date);

CREATE TRIGGER trg_tenders_updated_at
BEFORE UPDATE ON tenders
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();


-- ============================================================
-- Table: tender_documents
-- ============================================================

CREATE TABLE tender_documents (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    tender_id BIGINT NOT NULL,

    media_file_id BIGINT NOT NULL,

    title VARCHAR(200) NOT NULL,

    display_order INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tender_documents PRIMARY KEY (id),

    CONSTRAINT fk_tender_documents_tender
        FOREIGN KEY (tender_id)
        REFERENCES tenders(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_tender_documents_media
        FOREIGN KEY (media_file_id)
        REFERENCES media_files(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_tender_documents_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_tender_documents_tender
ON tender_documents(tender_id);

CREATE TRIGGER trg_tender_documents_updated_at
BEFORE UPDATE ON tender_documents
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();