-- ============================================================
-- Project      : NHPC Website
-- File         : 08_careers.sql
-- Module       : Careers
-- Description  : Job Openings, Documents & Applications
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: job_openings
-- ============================================================

CREATE TABLE job_openings (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    title VARCHAR(255) NOT NULL,

    slug VARCHAR(255) NOT NULL,

    employment_type_id BIGINT NOT NULL,

    location VARCHAR(150),

    vacancies INTEGER,

    summary TEXT,

    description TEXT,

    published_at TIMESTAMPTZ,

    application_deadline DATE,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_job_openings PRIMARY KEY (id),

    CONSTRAINT uq_job_openings_slug UNIQUE (slug),

    CONSTRAINT fk_job_openings_employment_type
        FOREIGN KEY (employment_type_id)
        REFERENCES employment_types(id),

    CONSTRAINT chk_job_openings_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_job_openings_slug
ON job_openings(slug);

CREATE INDEX idx_job_openings_employment_type
ON job_openings(employment_type_id);

CREATE INDEX idx_job_openings_deadline
ON job_openings(application_deadline);

CREATE TRIGGER trg_job_openings_updated_at
BEFORE UPDATE ON job_openings
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: job_documents
-- ============================================================

CREATE TABLE job_documents (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    job_opening_id BIGINT NOT NULL,

    media_file_id BIGINT NOT NULL,

    title VARCHAR(200) NOT NULL,

    display_order INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_job_documents PRIMARY KEY (id),

    CONSTRAINT fk_job_documents_job
        FOREIGN KEY (job_opening_id)
        REFERENCES job_openings(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_job_documents_media
        FOREIGN KEY (media_file_id)
        REFERENCES media_files(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_job_documents_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_job_documents_job
ON job_documents(job_opening_id);

CREATE TRIGGER trg_job_documents_updated_at
BEFORE UPDATE ON job_documents
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: job_applications
-- ============================================================

CREATE TABLE job_applications (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    job_opening_id BIGINT NOT NULL,

    full_name VARCHAR(150) NOT NULL,

    email VARCHAR(255) NOT NULL,

    phone VARCHAR(20) NOT NULL,

    address TEXT,

    experience_years NUMERIC(4,1),

    resume_media_file_id BIGINT NOT NULL,

    cover_letter TEXT,

    application_status_id BIGINT NOT NULL,

    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_job_applications PRIMARY KEY (id),

    CONSTRAINT fk_job_applications_job
        FOREIGN KEY (job_opening_id)
        REFERENCES job_openings(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_job_applications_resume
        FOREIGN KEY (resume_media_file_id)
        REFERENCES media_files(id),

    CONSTRAINT fk_job_applications_status
        FOREIGN KEY (application_status_id)
        REFERENCES application_statuses(id)

);

CREATE INDEX idx_job_applications_job
ON job_applications(job_opening_id);

CREATE INDEX idx_job_applications_email
ON job_applications(email);

CREATE INDEX idx_job_applications_status
ON job_applications(application_status_id);

CREATE TRIGGER trg_job_applications_updated_at
BEFORE UPDATE ON job_applications
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();