-- ============================================================
-- Project      : NHPC Website
-- File         : 09_investors.sql
-- Module       : Investors
-- Description  : Investor Documents & Highlights
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: investor_documents
-- ============================================================

CREATE TABLE investor_documents (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    title VARCHAR(255) NOT NULL,

    investor_document_type_id BIGINT NOT NULL,

    financial_year_id BIGINT,

    description TEXT,

    media_file_id BIGINT NOT NULL,

    published_at TIMESTAMPTZ,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_investor_documents
        PRIMARY KEY(id),

    CONSTRAINT fk_investor_documents_type
        FOREIGN KEY(investor_document_type_id)
        REFERENCES investor_document_types(id),

    CONSTRAINT fk_investor_documents_year
        FOREIGN KEY(financial_year_id)
        REFERENCES financial_years(id),

    CONSTRAINT fk_investor_documents_media
        FOREIGN KEY(media_file_id)
        REFERENCES media_files(id),

    CONSTRAINT chk_investor_documents_display_order
        CHECK(display_order > 0)

);

CREATE INDEX idx_investor_documents_type
ON investor_documents(investor_document_type_id);

CREATE INDEX idx_investor_documents_year
ON investor_documents(financial_year_id);

CREATE INDEX idx_investor_documents_published
ON investor_documents(published_at);

CREATE TRIGGER trg_investor_documents_updated_at
BEFORE UPDATE ON investor_documents
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: investor_highlights
-- ============================================================

CREATE TABLE investor_highlights (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    financial_year_id BIGINT NOT NULL,

    metric_name VARCHAR(150) NOT NULL,

    metric_value VARCHAR(100) NOT NULL,

    unit VARCHAR(50),

    display_order INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_investor_highlights
        PRIMARY KEY(id),

    CONSTRAINT fk_investor_highlights_year
        FOREIGN KEY(financial_year_id)
        REFERENCES financial_years(id),

    CONSTRAINT chk_investor_highlights_display_order
        CHECK(display_order > 0)

);

CREATE INDEX idx_investor_highlights_year
ON investor_highlights(financial_year_id);

CREATE INDEX idx_investor_highlights_metric
ON investor_highlights(metric_name);

CREATE TRIGGER trg_investor_highlights_updated_at
BEFORE UPDATE ON investor_highlights
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();