-- ============================================================
-- Project      : NHPC Website
-- File         : 10_contact.sql
-- Module       : Contact
-- Description  : Offices & Contact Messages
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: offices
-- ============================================================

CREATE TABLE offices (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    office_type_id BIGINT NOT NULL,

    name VARCHAR(255) NOT NULL,

    address TEXT NOT NULL,

    city VARCHAR(100) NOT NULL,

    state_id BIGINT NOT NULL,

    pincode VARCHAR(15),

    phone VARCHAR(30),

    email VARCHAR(255),

    latitude DECIMAL(10,7),

    longitude DECIMAL(10,7),

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_offices
        PRIMARY KEY(id),

    CONSTRAINT fk_offices_type
        FOREIGN KEY(office_type_id)
        REFERENCES office_types(id),

    CONSTRAINT fk_offices_state
        FOREIGN KEY(state_id)
        REFERENCES states(id),

    CONSTRAINT chk_offices_display_order
        CHECK(display_order > 0)

);

CREATE INDEX idx_offices_type
ON offices(office_type_id);

CREATE INDEX idx_offices_state
ON offices(state_id);

CREATE INDEX idx_offices_active
ON offices(is_active);

CREATE TRIGGER trg_offices_updated_at
BEFORE UPDATE ON offices
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();

-- ============================================================
-- Table: contact_messages
-- ============================================================

CREATE TABLE contact_messages (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    full_name VARCHAR(150) NOT NULL,

    email VARCHAR(255) NOT NULL,

    phone VARCHAR(20),

    department VARCHAR(100),

    subject VARCHAR(255) NOT NULL,

    message TEXT NOT NULL,

    message_status_id BIGINT NOT NULL,

    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_contact_messages
        PRIMARY KEY(id),

    CONSTRAINT fk_contact_messages_status
        FOREIGN KEY(message_status_id)
        REFERENCES message_statuses(id)

);

CREATE INDEX idx_contact_messages_email
ON contact_messages(email);

CREATE INDEX idx_contact_messages_status
ON contact_messages(message_status_id);

CREATE INDEX idx_contact_messages_submitted
ON contact_messages(submitted_at);

CREATE TRIGGER trg_contact_messages_updated_at
BEFORE UPDATE ON contact_messages
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();