-- ============================================================
-- Project      : NHPC Website
-- File         : 11_leadership.sql
-- Module       : Leadership
-- Description  : Leadership & Board Members
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: leadership
-- ============================================================

CREATE TABLE leadership (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    full_name VARCHAR(200) NOT NULL,

    slug VARCHAR(250) NOT NULL,

    designation VARCHAR(200) NOT NULL,

    leadership_level_id BIGINT NOT NULL,

    qualification TEXT,

    experience_summary TEXT,

    description TEXT,

    email VARCHAR(255),

    phone VARCHAR(30),

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_leadership
        PRIMARY KEY (id),

    CONSTRAINT uq_leadership_slug
        UNIQUE (slug),

    CONSTRAINT fk_leadership_level
        FOREIGN KEY (leadership_level_id)
        REFERENCES leadership_levels(id),

    CONSTRAINT chk_leadership_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_leadership_slug
ON leadership(slug);

CREATE INDEX idx_leadership_level
ON leadership(leadership_level_id);

CREATE INDEX idx_leadership_active
ON leadership(is_active);

CREATE INDEX idx_leadership_display_order
ON leadership(display_order);

CREATE TRIGGER trg_leadership_updated_at
BEFORE UPDATE ON leadership
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();