-- ============================================================
-- Project      : NHPC Website
-- File         : 12_sustainability.sql
-- Module       : Sustainability
-- Description  : Sustainability Initiatives
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: sustainability
-- ============================================================

CREATE TABLE sustainability (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    title VARCHAR(255) NOT NULL,

    slug VARCHAR(255) NOT NULL,

    sustainability_type_id BIGINT NOT NULL,

    summary TEXT,

    description TEXT,

    published_at TIMESTAMPTZ,

    is_featured BOOLEAN NOT NULL DEFAULT FALSE,

    display_order INTEGER NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_sustainability
        PRIMARY KEY (id),

    CONSTRAINT uq_sustainability_slug
        UNIQUE (slug),

    CONSTRAINT fk_sustainability_type
        FOREIGN KEY (sustainability_type_id)
        REFERENCES sustainability_types(id),

    CONSTRAINT chk_sustainability_display_order
        CHECK (display_order > 0)

);

CREATE INDEX idx_sustainability_slug
ON sustainability(slug);

CREATE INDEX idx_sustainability_type
ON sustainability(sustainability_type_id);

CREATE INDEX idx_sustainability_featured
ON sustainability(is_featured);

CREATE INDEX idx_sustainability_active
ON sustainability(is_active);

CREATE INDEX idx_sustainability_published
ON sustainability(published_at);

CREATE TRIGGER trg_sustainability_updated_at
BEFORE UPDATE ON sustainability
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();