-- ============================================================
-- Project      : NHPC Website
-- File         : 13_settings.sql
-- Module       : Application Settings
-- Description  : Global Website Configuration
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: settings
-- ============================================================

CREATE TABLE settings (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    setting_key VARCHAR(100) NOT NULL,

    setting_value TEXT,

    setting_type VARCHAR(30) NOT NULL DEFAULT 'TEXT',

    description TEXT,

    is_public BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_settings
        PRIMARY KEY (id),

    CONSTRAINT uq_settings_key
        UNIQUE (setting_key),

    CONSTRAINT chk_settings_type
        CHECK (
            setting_type IN (
                'TEXT',
                'NUMBER',
                'BOOLEAN',
                'EMAIL',
                'URL',
                'MEDIA'
            )
        )

);

CREATE INDEX idx_settings_key
ON settings(setting_key);

CREATE INDEX idx_settings_public
ON settings(is_public);

CREATE TRIGGER trg_settings_updated_at
BEFORE UPDATE ON settings
FOR EACH ROW
EXECUTE FUNCTION fn_update_updated_at();