-- ============================================================
-- Project      : NHPC Website
-- File         : 14_audit_logs.sql
-- Module       : Audit Logs
-- Description  : Tracks administrative actions
-- Database     : PostgreSQL 18+
-- ============================================================

SET TIME ZONE 'UTC';

-- ============================================================
-- Table: audit_logs
-- ============================================================

CREATE TABLE audit_logs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    admin_id BIGINT NOT NULL,

    action VARCHAR(50) NOT NULL,

    entity_type VARCHAR(100) NOT NULL,

    entity_id BIGINT NOT NULL,

    old_data JSONB,

    new_data JSONB,

    ip_address INET,

    user_agent TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_audit_logs
        PRIMARY KEY (id),

    CONSTRAINT fk_audit_logs_admin
        FOREIGN KEY (admin_id)
        REFERENCES admins(id),

    CONSTRAINT chk_audit_logs_action
        CHECK (
            action IN (
                'CREATE',
                'UPDATE',
                'DELETE',
                'LOGIN',
                'LOGOUT',
                'PUBLISH',
                'UNPUBLISH',
                'PASSWORD_CHANGE',
                'PASSWORD_RESET',
                'ROLE_CHANGE',
                'UPLOAD_MEDIA',
                'DELETE_MEDIA'
            )
        ),

    CONSTRAINT chk_audit_logs_entity_type
        CHECK (
            entity_type IN (
                'ADMIN',
                'HOMEPAGE',
                'PROJECT',
                'NEWS',
                'TENDER',
                'JOB_OPENING',
                'LEADERSHIP',
                'SUSTAINABILITY',
                'INVESTOR_DOCUMENT',
                'OFFICE',
                'SETTING',
                'MEDIA',
                'OPERATIONAL_POWER_STATION'
            )
        )

);

CREATE INDEX idx_audit_logs_admin
ON audit_logs(admin_id);

CREATE INDEX idx_audit_logs_admin_created
ON audit_logs(admin_id, created_at DESC);

CREATE INDEX idx_audit_logs_entity
ON audit_logs(entity_type, entity_id);

CREATE INDEX idx_audit_logs_action
ON audit_logs(action);

CREATE INDEX idx_audit_logs_ip
ON audit_logs(ip_address);

CREATE INDEX idx_audit_logs_created_at
ON audit_logs(created_at DESC);